name: "Automatic Releaser"

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  releaser:
    uses: vultr/shared-actions/.github/workflows/go-releaser.yml@main
    secrets: inherit
    with:
      go_version: "1.24"
